/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsFoundation/PBXProjectItem.h>
#import <DevToolsFoundation/PBXMarkerDelegateProtocol.h>

@class PBXProject, PBXTextBookmark, XCBreakpointCondition;

@interface PBXBreakpoint : PBXProjectItem<PBXMarkerDelegateProtocol>

@property int breakpointStyle;

@property NSInteger ignoreCount;

@property NSTimeInterval delayBeforeContinue;

@property BOOL continueAfterActions;

@property (nonatomic, retain) NSString *comments;

@property (nonatomic, retain) NSString *name;

@property (nonatomic, getter = isEnabled) BOOL enabled;

@property (nonatomic) PBXMarkerState state;

@property (nonatomic, retain) PBXTextBookmark *textMark;

- (NSComparisonResult)compareToBreakpoint: (id)breakpoint;


@end

