/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsFoundation/PBXBreakpoint.h>

@interface PBXFileBreakpoint : PBXBreakpoint <NSCopying>

- (void)purify;

- (NSInteger)compareUsingLineNumber: (id)breakpoint;

- (NSInteger)compareToBreakpoint: (id)arg1;

@property (nonatomic, retain) id fileReference;
@property (nonatomic, retain) NSString * functionName;

- (id)initWithFileReference: (id)fileReference
                 lineNumber: (NSUInteger)lineNumber;

@end

