/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

enum
{
    PBXMarkerStateNormal = 1,
    PBXMarkerStateDisabled = 2,
};

typedef NSUInteger PBXMarkerState;

@protocol PBXMarkerDelegateProtocol <NSObject>

- (PBXMarkerState)state;

- (BOOL)isEnabled;

- (void)markChanged;

@property (nonatomic, assign) NSUInteger lineNumber;

@end

